name: Reusable workflow
#this is a sample for reusable code
on: 
  workflow_call:
    inputs: 
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current_time:
        description: 'The current time when greeting '
        value: ${{ jobs.reusable-job.outputs.current-time }}
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

